exclude_patterns:
  - benchmarks/*.rb
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  flog:
    enabled: true
    config:
      score_threshold: 20.0
  reek:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
