name: Verify code
on:
  push:
    branches: [development]
jobs:
  rspec:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 3.0.3
    - run: bundle exec rake rspec
      env:
        COVERAGE: 'true'
    - run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/coverage.xml || true
      env:
        CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 3.0.3
    - run: bundle exec rake rubocop

  doctest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 3.0.3
    - run: bundle exec rake yard:doctest

  deploy:
    concurrency:
      group: deploy
      cancel-in-progress: true
    needs: [rspec, rubocop, doctest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.0.3

      - name: Bump gem version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          bundle exec bump patch --changelog

      - name: Build gem and release to Rubygems
        uses: cadwallion/publish-rubygems-action@master
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push code to main
        run: git push origin -f development:main --follow-tags

      - name: Get current gem version
        run: echo "::set-output name=version::$(bundle exec bump current)"
        id: gem

      - name: Create github release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: Release ${{ steps.gem.outputs.version }}
          tag_name: v${{ steps.gem.outputs.version }}
          prerelease: false
          draft: false

  docs:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 3.0.3
    - name: Build docs
      run: |
        bundle exec rake yard:docs
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add docs/
        git commit -m 'update docs'
        git push -f origin development:gh-pages
