name: Main
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.0
      - run: bundle exec rspec --format RSpec::Github::Formatter
      - name: badge-it
        uses: rocktimsaikia/badge-it@2.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          badges: 'gh_license, gh_version, gh_stars'
          badge-style: 'flat-square'

      - name: RuboCop
        uses: andrewmcodes-archive/rubocop-linter-action@v3.3.0


