name: Verify code
on:
  push:
    branches: [development]
jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 3.0.3
    - run: bundle exec rake rspec
      env:
        COVERAGE: 'true'
    - run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/coverage.xml || true
      env:
        CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 3.0.3
    - run: bundle exec rake rubocop

  doctest:
    runs-on: ubuntu-latest
    needs: [rspec]
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 3.0.3
    - run: bundle exec rake yard:doctest

  deploy:
    concurrency:
      group: deploy
      cancel-in-progress: true
    needs: [rspec, rubocop]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.0.3

      - name: Bump gem version
        run: |
          git config --local user.email "bot@oleander.io"
          git config --local user.name "oleander-bot"
          bundle exec bump patch --changelog

      - name: Build gem and release to Rubygems
        uses: cadwallion/publish-rubygems-action@master
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git push origin -f development:main --follow-tags

      - name: Get current gem version
        run: echo "::set-output name=version::$(bundle exec bump current)"
        id: gem

      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: Release ${{ steps.gem.outputs.version }}
          tag_name: v${{ steps.gem.outputs.version }}
          prerelease: false
          draft: false
