name: remap
on: [push]
jobs:
  rspec:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 3.0.3
    - run: bundle exec rake rspec

  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 3.0.3
    - run: bundle exec rake rubocop

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 3.0.3
    - run: bundle exec rake yard:docs

    - run: git config --local user.email "bot@oleander.io"
    - run: git config --local user.name "oleander-bot"

    - run: git add docs/

    - run: git commit -m 'update docs'
    - run: git push -f origin development:gh-pages
  doctest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 3.0.3
    - run: bundle exec rake yard:doctest


